"""30 hand-written easy Python katas with visible + hidden tests."""

HAND_KATAS = [
    {
        "id": "hand_001",
        "prompt": "Write is_palindrome(s) that returns True if s reads the same forwards and backwards, ignoring case and spaces.",
        "entry_point": "is_palindrome",
        "tests": [
            "assert is_palindrome('aba') is True",
            "assert is_palindrome('ab') is False",
        ],
        "hidden_tests": [
            "assert is_palindrome('A man a plan a canal Panama') is True",
            "assert is_palindrome('') is True",
            "assert is_palindrome('Aa') is True",
        ],
        "solution": "def is_palindrome(s):\n    t = ''.join(ch.lower() for ch in s if not ch.isspace())\n    return t == t[::-1]\n",
        "tags": ["strings"],
    },
    {
        "id": "hand_002",
        "prompt": "Write add(a, b) returning the sum of two numbers.",
        "entry_point": "add",
        "tests": ["assert add(1, 2) == 3", "assert add(0, 0) == 0"],
        "hidden_tests": ["assert add(-4, 10) == 6", "assert add(1.5, 2.5) == 4.0"],
        "solution": "def add(a, b):\n    return a + b\n",
        "tags": ["math"],
    },
    {
        "id": "hand_003",
        "prompt": "Write fizzbuzz(n) returning 'Fizz' if n divisible by 3, 'Buzz' by 5, 'FizzBuzz' by both, else str(n).",
        "entry_point": "fizzbuzz",
        "tests": ["assert fizzbuzz(3) == 'Fizz'", "assert fizzbuzz(5) == 'Buzz'", "assert fizzbuzz(1) == '1'"],
        "hidden_tests": ["assert fizzbuzz(15) == 'FizzBuzz'", "assert fizzbuzz(7) == '7'"],
        "solution": "def fizzbuzz(n):\n    if n % 15 == 0:\n        return 'FizzBuzz'\n    if n % 3 == 0:\n        return 'Fizz'\n    if n % 5 == 0:\n        return 'Buzz'\n    return str(n)\n",
        "tags": ["math"],
    },
    {
        "id": "hand_004",
        "prompt": "Write factorial(n) for n >= 0. 0! is 1.",
        "entry_point": "factorial",
        "tests": ["assert factorial(0) == 1", "assert factorial(5) == 120"],
        "hidden_tests": ["assert factorial(1) == 1", "assert factorial(7) == 5040"],
        "solution": "def factorial(n):\n    r = 1\n    for i in range(2, n + 1):\n        r *= i\n    return r\n",
        "tags": ["math"],
    },
    {
        "id": "hand_005",
        "prompt": "Write reverse_string(s) that returns s reversed.",
        "entry_point": "reverse_string",
        "tests": ["assert reverse_string('ab') == 'ba'", "assert reverse_string('') == ''"],
        "hidden_tests": ["assert reverse_string('xyz') == 'zyx'"],
        "solution": "def reverse_string(s):\n    return s[::-1]\n",
        "tags": ["strings"],
    },
    {
        "id": "hand_006",
        "prompt": "Write count_vowels(s) counting aeiou (case-insensitive).",
        "entry_point": "count_vowels",
        "tests": ["assert count_vowels('hello') == 2", "assert count_vowels('xyz') == 0"],
        "hidden_tests": ["assert count_vowels('AEIOU') == 5", "assert count_vowels('') == 0"],
        "solution": "def count_vowels(s):\n    return sum(ch.lower() in 'aeiou' for ch in s)\n",
        "tags": ["strings"],
    },
    {
        "id": "hand_007",
        "prompt": "Write max_of_two(a, b) returning the larger value.",
        "entry_point": "max_of_two",
        "tests": ["assert max_of_two(1, 2) == 2", "assert max_of_two(3, 3) == 3"],
        "hidden_tests": ["assert max_of_two(-1, -8) == -1"],
        "solution": "def max_of_two(a, b):\n    return a if a >= b else b\n",
        "tags": ["math"],
    },
    {
        "id": "hand_008",
        "prompt": "Write is_even(n) returning True iff n is even.",
        "entry_point": "is_even",
        "tests": ["assert is_even(2) is True", "assert is_even(3) is False"],
        "hidden_tests": ["assert is_even(0) is True", "assert is_even(-4) is True"],
        "solution": "def is_even(n):\n    return n % 2 == 0\n",
        "tags": ["math"],
    },
    {
        "id": "hand_009",
        "prompt": "Write sum_list(xs) returning the sum of numbers in xs. Empty list sums to 0.",
        "entry_point": "sum_list",
        "tests": ["assert sum_list([1, 2, 3]) == 6", "assert sum_list([]) == 0"],
        "hidden_tests": ["assert sum_list([-1, 1]) == 0"],
        "solution": "def sum_list(xs):\n    return sum(xs)\n",
        "tags": ["lists"],
    },
    {
        "id": "hand_010",
        "prompt": "Write unique_preserve(xs) returning xs with duplicates removed, first-seen order kept.",
        "entry_point": "unique_preserve",
        "tests": ["assert unique_preserve([1, 1, 2]) == [1, 2]"],
        "hidden_tests": [
            "assert unique_preserve(['a', 'b', 'a']) == ['a', 'b']",
            "assert unique_preserve([]) == []",
        ],
        "solution": "def unique_preserve(xs):\n    out, seen = [], set()\n    for x in xs:\n        if x not in seen:\n            seen.add(x)\n            out.append(x)\n    return out\n",
        "tags": ["lists"],
    },
    {
        "id": "hand_011",
        "prompt": "Write flatten_one(xs) flattening one level of nested lists.",
        "entry_point": "flatten_one",
        "tests": ["assert flatten_one([[1, 2], [3]]) == [1, 2, 3]"],
        "hidden_tests": ["assert flatten_one([[], [1], []]) == [1]"],
        "solution": "def flatten_one(xs):\n    out = []\n    for x in xs:\n        out.extend(x)\n    return out\n",
        "tags": ["lists"],
    },
    {
        "id": "hand_012",
        "prompt": "Write word_count(s) returning the number of whitespace-separated words. Extra spaces ignored.",
        "entry_point": "word_count",
        "tests": ["assert word_count('hello world') == 2", "assert word_count('') == 0"],
        "hidden_tests": ["assert word_count('  a   b  ') == 2"],
        "solution": "def word_count(s):\n    return len(s.split())\n",
        "tags": ["strings"],
    },
    {
        "id": "hand_013",
        "prompt": "Write celsius_to_fahrenheit(c) using F = C * 9/5 + 32.",
        "entry_point": "celsius_to_fahrenheit",
        "tests": ["assert celsius_to_fahrenheit(0) == 32", "assert celsius_to_fahrenheit(100) == 212"],
        "hidden_tests": ["assert celsius_to_fahrenheit(-40) == -40"],
        "solution": "def celsius_to_fahrenheit(c):\n    return c * 9 / 5 + 32\n",
        "tags": ["math"],
    },
    {
        "id": "hand_014",
        "prompt": "Write is_anagram(a, b) True if a and b use the same letters ignoring case and spaces.",
        "entry_point": "is_anagram",
        "tests": ["assert is_anagram('ab', 'ba') is True", "assert is_anagram('ab', 'aa') is False"],
        "hidden_tests": ["assert is_anagram('Listen', 'Silent') is True"],
        "solution": "def is_anagram(a, b):\n    def norm(s):\n        return sorted(ch.lower() for ch in s if not ch.isspace())\n    return norm(a) == norm(b)\n",
        "tags": ["strings"],
    },
    {
        "id": "hand_015",
        "prompt": "Write fibonacci(n) returning the n-th Fibonacci number with fibonacci(0)=0, fibonacci(1)=1.",
        "entry_point": "fibonacci",
        "tests": ["assert fibonacci(0) == 0", "assert fibonacci(1) == 1", "assert fibonacci(6) == 8"],
        "hidden_tests": ["assert fibonacci(10) == 55"],
        "solution": "def fibonacci(n):\n    a, b = 0, 1\n    for _ in range(n):\n        a, b = b, a + b\n    return a\n",
        "tags": ["math"],
    },
    {
        "id": "hand_016",
        "prompt": "Write clamp(x, lo, hi) that clips x into [lo, hi].",
        "entry_point": "clamp",
        "tests": ["assert clamp(5, 0, 10) == 5", "assert clamp(-1, 0, 10) == 0"],
        "hidden_tests": ["assert clamp(99, 0, 10) == 10"],
        "solution": "def clamp(x, lo, hi):\n    return max(lo, min(hi, x))\n",
        "tags": ["math"],
    },
    {
        "id": "hand_017",
        "prompt": "Write title_words(s) capitalizing the first letter of each whitespace-separated word, lowercasing the rest.",
        "entry_point": "title_words",
        "tests": ["assert title_words('hello world') == 'Hello World'"],
        "hidden_tests": ["assert title_words('a') == 'A'", "assert title_words('ABC def') == 'Abc Def'"],
        "solution": "def title_words(s):\n    return ' '.join(w[:1].upper() + w[1:].lower() if w else w for w in s.split(' '))\n",
        "tags": ["strings"],
    },
    {
        "id": "hand_018",
        "prompt": "Write mean(xs) returning the arithmetic mean of a non-empty list of numbers.",
        "entry_point": "mean",
        "tests": ["assert mean([1, 2, 3]) == 2", "assert mean([2, 2]) == 2"],
        "hidden_tests": ["assert abs(mean([1, 2]) - 1.5) < 1e-9"],
        "solution": "def mean(xs):\n    return sum(xs) / len(xs)\n",
        "tags": ["math", "lists"],
    },
    {
        "id": "hand_019",
        "prompt": "Write median(xs) for a non-empty list. For even length, average the two middle values after sorting.",
        "entry_point": "median",
        "tests": ["assert median([1, 3, 2]) == 2", "assert median([1, 2]) == 1.5"],
        "hidden_tests": ["assert median([5]) == 5"],
        "solution": "def median(xs):\n    ys = sorted(xs)\n    n = len(ys)\n    mid = n // 2\n    if n % 2:\n        return ys[mid]\n    return (ys[mid - 1] + ys[mid]) / 2\n",
        "tags": ["math", "lists"],
    },
    {
        "id": "hand_020",
        "prompt": "Write gcd(a, b) returning the greatest common divisor of two non-negative integers. gcd(0, n) is n.",
        "entry_point": "gcd",
        "tests": ["assert gcd(12, 8) == 4", "assert gcd(7, 1) == 1"],
        "hidden_tests": ["assert gcd(0, 5) == 5", "assert gcd(21, 14) == 7"],
        "solution": "def gcd(a, b):\n    while b:\n        a, b = b, a % b\n    return a\n",
        "tags": ["math"],
    },
    {
        "id": "hand_021",
        "prompt": "Write lcm(a, b) for positive integers using lcm(a,b)=abs(a*b)//gcd(a,b).",
        "entry_point": "lcm",
        "tests": ["assert lcm(4, 6) == 12", "assert lcm(5, 1) == 5"],
        "hidden_tests": ["assert lcm(7, 3) == 21"],
        "solution": "def lcm(a, b):\n    x, y = a, b\n    while y:\n        x, y = y, x % y\n    return abs(a * b) // x\n",
        "tags": ["math"],
    },
    {
        "id": "hand_022",
        "prompt": "Write is_prime(n) True iff n is a prime integer. Numbers < 2 are not prime.",
        "entry_point": "is_prime",
        "tests": ["assert is_prime(2) is True", "assert is_prime(1) is False", "assert is_prime(9) is False"],
        "hidden_tests": ["assert is_prime(13) is True", "assert is_prime(0) is False"],
        "solution": "def is_prime(n):\n    if n < 2:\n        return False\n    if n % 2 == 0:\n        return n == 2\n    i = 3\n    while i * i <= n:\n        if n % i == 0:\n            return False\n        i += 2\n    return True\n",
        "tags": ["math"],
    },
    {
        "id": "hand_023",
        "prompt": "Write digit_sum(n) summing the decimal digits of a non-negative integer.",
        "entry_point": "digit_sum",
        "tests": ["assert digit_sum(123) == 6", "assert digit_sum(0) == 0"],
        "hidden_tests": ["assert digit_sum(999) == 27"],
        "solution": "def digit_sum(n):\n    return sum(int(ch) for ch in str(n))\n",
        "tags": ["math"],
    },
    {
        "id": "hand_024",
        "prompt": "Write last_n(xs, n) returning the last n items of xs. If n is larger than len(xs), return a copy of xs.",
        "entry_point": "last_n",
        "tests": ["assert last_n([1, 2, 3, 4], 2) == [3, 4]", "assert last_n([1], 5) == [1]"],
        "hidden_tests": ["assert last_n([], 3) == []"],
        "solution": "def last_n(xs, n):\n    return list(xs[-n:]) if n else []\n",
        "tags": ["lists"],
    },
    {
        "id": "hand_025",
        "prompt": "Write starts_with(s, prefix) returning True if s starts with prefix.",
        "entry_point": "starts_with",
        "tests": ["assert starts_with('hello', 'he') is True", "assert starts_with('hello', 'lo') is False"],
        "hidden_tests": ["assert starts_with('', '') is True"],
        "solution": "def starts_with(s, prefix):\n    return s.startswith(prefix)\n",
        "tags": ["strings"],
    },
    {
        "id": "hand_026",
        "prompt": "Write dict_get(d, key, default=None) returning d[key] if present else default.",
        "entry_point": "dict_get",
        "tests": ["assert dict_get({'a': 1}, 'a') == 1", "assert dict_get({'a': 1}, 'b', 0) == 0"],
        "hidden_tests": ["assert dict_get({}, 'x') is None"],
        "solution": "def dict_get(d, key, default=None):\n    return d[key] if key in d else default\n",
        "tags": ["dicts"],
    },
    {
        "id": "hand_027",
        "prompt": "Write filter_even(xs) returning a new list of the even integers in xs, same order.",
        "entry_point": "filter_even",
        "tests": ["assert filter_even([1, 2, 3, 4]) == [2, 4]"],
        "hidden_tests": ["assert filter_even([1, 3]) == []", "assert filter_even([]) == []"],
        "solution": "def filter_even(xs):\n    return [x for x in xs if x % 2 == 0]\n",
        "tags": ["lists"],
    },
    {
        "id": "hand_028",
        "prompt": "Write map_square(xs) returning a new list of each number squared.",
        "entry_point": "map_square",
        "tests": ["assert map_square([1, 2, 3]) == [1, 4, 9]"],
        "hidden_tests": ["assert map_square([]) == []", "assert map_square([-2]) == [4]"],
        "solution": "def map_square(xs):\n    return [x * x for x in xs]\n",
        "tags": ["lists"],
    },
    {
        "id": "hand_029",
        "prompt": "Write intersection(a, b) returning a list of items in both lists, unique, order of first appearance in a.",
        "entry_point": "intersection",
        "tests": ["assert intersection([1, 2, 3], [2, 3, 4]) == [2, 3]"],
        "hidden_tests": [
            "assert intersection([1, 1, 2], [1]) == [1]",
            "assert intersection([1], [2]) == []",
        ],
        "solution": "def intersection(a, b):\n    sb = set(b)\n    out, seen = [], set()\n    for x in a:\n        if x in sb and x not in seen:\n            seen.add(x)\n            out.append(x)\n    return out\n",
        "tags": ["lists"],
    },
    {
        "id": "hand_030",
        "prompt": "Write most_common_char(s) returning the most frequent alphabetic character (case-insensitive). Ties: the earliest in the alphabet. Ignore non-letters. Empty/no letters -> ''.",
        "entry_point": "most_common_char",
        "tests": ["assert most_common_char('aab') == 'a'", "assert most_common_char('') == ''"],
        "hidden_tests": [
            "assert most_common_char('Bba') == 'b'",
            "assert most_common_char('cba') == 'a'",
            "assert most_common_char('123') == ''",
        ],
        "solution": "def most_common_char(s):\n    counts = {}\n    for ch in s:\n        if ch.isalpha():\n            k = ch.lower()\n            counts[k] = counts.get(k, 0) + 1\n    if not counts:\n        return ''\n    best = min(counts.items(), key=lambda kv: (-kv[1], kv[0]))\n    return best[0]\n",
        "tags": ["strings"],
    },
]
